title: ""
description: "Cybersecurity Labs"
url: "https://julmgc.github.io"
baseurl: ""

sass:
  sass_dir: _sass

remote_theme: "mmistakes/minimal-mistakes@4.24.0"

minimal_mistakes_skin: "contrast"
search: true
breadcrumbs: true

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-archives
  - jekyll-paginate
  - jekyll-include-cache

collections:
  pages:
    output: true
    permalink: /:path/

# paginate: 5
# paginate_path: /assets/_images/lock.jpg

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      permalink: /:categories/:title/
      author_profile: true
      read_time: true
      show_date: false
      toc: true
      toc_sticky: true
      sidebar:
        nav: "sidebar"

author:
  name: "Julia Clepf"
  avatar: "/assets/images/avatar.jpeg"
  bio: "Cybersecurity student with a background in web development, passionate about ethical hacking ğŸ•µï¸â€â™€ï¸"
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/Julmgc"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://linkedin.com/in/your-link"
